20240117の取り組み
uemura1999/note pull request #22
Opened 2024-01-17 16:42 UTC by uemura1999

2024-01-17 23:37 UTC, n350071 requested changes
流し読みのつもりが、良い内容だったので、ガッツリコメントしてしまいました。

2024-01-17 23:37 UTC, n350071 commented on todo/20240117.md
よい学びを得ましたね。

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +      - 送信先を確認
### [追記依頼]

#### コメント
メールとSMSは、セキュリティホールになりがちなので、
なるべく、メールでの連絡は控えるようにしてください。

たとえば、メールでファイルを送られてきても開かないとか、Slackで送るようにお願いするとか、です。

...とはいえ、この考え方は、まだ常識になっていないので、現場では実践するにはちょっと勇気がいるかと思います。迷ったときは相談してください。

#### 追記内容
上記のコメントについて、石垣と会話をして、学んだことを追記しましょう。

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +        - WPA2またはWPA3を選択
### [確認と追記依頼]
#### 確認内容
WPA2 WPA3 は強固な暗号化方式だったと思います。
一方で、弱いな暗号化方式はなんでしょうか？ （ヒント: `W..` 方式）
弱い方式は、危ない...と認識してもらえたらOKです。

#### 追記内容
確認したことを追記しましょう

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +      - 立ち入り制限
### [口頭確認依頼]
#### コメント
立ち入り制限とはどのようなものでしょうか？
また、立ち入り制限をしているものの、その目的を果たせていないパターンを想像してください。

#### 口頭ですること
これを、石垣に説明してください。

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +      - 盗難や紛失
### [追記依頼]
#### コメント
ChatGPTを使ってよいので、盗難や紛失のあるあるを２０件リストし、それぞれの概要と対策を１行程度ずつで書いてください。

#### アウトプットイメージ
- カフェでの紛失
  - カフェで作業中にトイレに行って帰ってきたら、パソコンがなくなっていた
  - パソコンをトイレに持ち込む or 物理的に運べないようにチェーンをつける
- 駐車場での紛失
  - コンビニの駐車場に停めて、鍵をかけずに、ジュースを買って帰ってきたら、助手席のリュックがなくなっていた
  - たとえ５分程度の離席であっても、パソコンを肌身離さず持ち歩くこと

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +      - 情報漏洩
これは、上村さん大丈夫そうですね。
居酒屋で話すときにも会社名を全部言わずに、「L社」などと言うようにしましょう。

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +    - 今までのセキュリティ対策をルール化して明示している
これは、石垣の宿題ですね。ありがとう。
いままでは水野くんと２人だけだったので不要でしたが、これから作成していきたいと思っています。
そのときは上村さんのノートを参考にしたいと思っています。よろしくお願いします。

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +  - パスワードを使い回す時もあったので、パスワード.mdを参考に常にパスワードを作成する
### [質問]
- これ口頭で説明を受けたい。
- もしかしたら、石垣が発明したパスワード管理法を伝授するかも

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/セキュリティ診断.md
> +  - 以前、石垣さんの家にPCを忘れてしまったので、今後はこういったことがないように指差し確認をする
こういうことをちゃんと書いてくれるので、信頼感がUPします👍

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/制御システム.md
> +    - USBメモリの利用制限
### [追記依頼]
#### コメント
空港やコワーキングスペース（FGN）などでは、電源コンセントのすぐ近くに、USB式の給電ポートが用意されていることが増えてきています。
しかし、攻撃者がUSBポートをいじることで、「充電だけしたつもりが、じつはマルウェアを注入されていた」という事態が発生します。

#### 追記すること
このことを追記してください。

2024-01-17 23:37 UTC, n350071 commented on セキュリティ/制御システム.md
> +- 製造業のお客様と話している時に、基本的なセキュリティの知識は持っておかないと信用問題に発展する可能性がある
製造業に限らずですが、我々は顧客から「詳しいなー、さすがだなー」と思ってもらえるレベルで知っておかないと、信用問題というか、不安にさせてしまうと思うので、頑張っていきましょう。

（石垣は、以前にゼロトラストを知らなかったのは後悔していて、あのあと勉強しました）

2024-01-27 06:21 UTC, uemura1999 commented on セキュリティ/セキュリティ診断.md
> +        - WPA2またはWPA3を選択
WEP方式を追記しました！

2024-01-27 06:37 UTC, uemura1999 commented on セキュリティ/セキュリティ診断.md
> +    - 今までのセキュリティ対策をルール化して明示している
セキュリティガイドとして上村が作成する

2024-01-29 08:56 UTC, n350071 commented
あれ...

https://github.com/uemura1999/note/pull/22
に修正をかける形でいいんだよ。

これ、DSMのときに伝えたい。

2024-01-31 09:58 UTC, merged