Feature9/20240206 security
uemura1999/note pull request #29
Opened 2024-02-07 01:40 UTC by uemura1999

## 対応内容

* IPAの情報セキュリティ対策についてまとめております。流し読みでOKです。
* IPAの情報漏洩の対策のしおりについてまとめております。流し読みOKです。

### 今後について
情報漏洩を防ぐためのセキュリティ対策は、似通っている部分も多いためまとめていきながら、情報セキュリティガイドの制作につなげていきたいです。

2024-02-12 01:31 UTC, n350071 requested changes
差分が、このようになっていて、もう１つのPRと被っているよ。

![Screenshot 2024-02-12 at 10 28 34](https://github.com/uemura1999/note/assets/5251488/2429ee35-fdf4-497e-9c40-1fd45d0658b0)


どうしてこうなったのか？説明できるかな？
コミット履歴を調べてみて、どうしたら、２つともレビュしてもらえる状況になるか？次からどうするか？を考えてみよう。

2024-02-12 01:34 UTC, n350071 reviewed
１つ前の要求がクリアされたら、Approveしますね。

2024-02-12 01:34 UTC, n350071 commented on セキュリティ/情報漏洩の対策のしおり.md
> +  - 事後対応
マジでこれ重要。隠すと、より肥大化する。

2024-02-12 07:33 UTC, uemura1999 commented
個別に送ったはずのPRが被っており、どこをみていいのかわからない
[原因]
git add . により、全てのファイルをstagingにあげてしまったため
[次回から気をつけること]
git add ファイル名とすることで、特定のファイルの差分のみをPRする

2024-02-13 02:15 UTC, n350071 approved these changes
口頭での補足をしますので、その後にマージOKです。
リマインドをお願いします。

### 話すこと
### 解決策に対する問題
git add [file_name] だと、１つのファイル内に複数ブランチの修正が混じっていたときに、正しく分けられるのか？
### 予想
ブランチ元がmainではなく、featureになっていないか？
### 手加減
ただし、いまは実際の開発とは違うので、いまは、問題がないのでこのままでもよい。
### 防ぎたいこと
上村さんが20時間かけて作ったfeature1とfeature2がこんがらがったり、石垣との作業がこんがらがって、やり直しになること

2024-02-13 04:50 UTC, merged